# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeniorAdvices',
            new_name='Advices',
        ),
    ]
