# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171010_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
