# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20171006_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_image',
            field=models.ImageField(upload_to='feed/static/images'),
        ),
    ]
