# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20171006_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_image',
            field=models.ImageField(upload_to='media/feed/static/images'),
        ),
    ]
