# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20171011_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
